# Generated by Django 4.0 on 2022-11-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recent_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Recent', 'Recent'), ('Canceled', 'Canceled'), ('Finished', 'Finished'), ('Revised', 'Revised')], default='Recent', max_length=200, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Recent_Order',
                'verbose_name_plural': 'Recent_Orders',
            },
        ),
    ]
