# Generated by Django 4.1 on 2022-08-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Recent', 'Recent'), ('Canceled', 'Canceled'), ('Finished', 'Finished')], default='Recent', max_length=200)),
                ('details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recent_Order',
                'verbose_name_plural': 'Recent_Orders',
            },
        ),
    ]
