# Generated by Django 4.1 on 2022-08-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_orders',
            name='amount',
        ),
    ]
