# Generated by Django 4.1 on 2022-08-22 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_academic_writing_user'),
        ('dashboard', '0002_remove_recent_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent_orders',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing'),
        ),
        migrations.AlterField(
            model_name='recent_orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
