# Generated by Django 4.1 on 2022-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_recent_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent_orders',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
