# Generated by Django 4.1 on 2022-08-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_recent_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_orders',
            name='user',
        ),
    ]
