# Generated by Django 4.1 on 2022-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_recent_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent_orders',
            name='status',
            field=models.CharField(blank=True, choices=[('Recent', 'Recent'), ('Canceled', 'Canceled'), ('Finished', 'Finished')], default='Recent', max_length=200, null=True),
        ),
    ]
