# Generated by Django 4.1 on 2022-08-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_recent_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent_orders',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='recent_orders',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
