# Generated by Django 4.1 on 2022-08-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_recent_orders_amount_recent_orders_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent_orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recent_orders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
