# Generated by Django 4.1 on 2022-08-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_recent_orders_created_at_recent_orders_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_orders',
            name='amount',
        ),
    ]
