# Generated by Django 4.0 on 2022-10-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_recent_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent_orders',
            name='status',
            field=models.CharField(blank=True, choices=[('Recent', 'Recent'), ('Canceled', 'Canceled'), ('Finished', 'Finished'), ('Revised', 'Revised')], default='Recent', max_length=200, null=True),
        ),
    ]
