# Generated by Django 4.1 on 2022-08-25 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('Academic Writing', 'Academic Writing'), ('Programming Assignment', 'Programming Assignment'), ('Calculations Assignment', 'Calculations Assignment')], default='Academic Writing', max_length=200)),
                ('academic_year', models.CharField(max_length=200)),
                ('deadline', models.CharField(blank=True, max_length=200, null=True)),
                ('paper_level', models.CharField(choices=[('Advanced', 'Advanced'), ('Standard', 'Standard'), ('Basic', 'Basic')], default='Standard', max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('upgrade', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic_Writing',
                'verbose_name_plural': 'Academic_Writing',
            },
        ),
        migrations.CreateModel(
            name='Academic_Writing_Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('instruction_file', models.FileField(blank=True, null=True, upload_to='')),
                ('paper_format', models.CharField(blank=True, max_length=200, null=True)),
                ('references', models.IntegerField(blank=True, default=0, null=True)),
                ('order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing')),
            ],
            options={
                'verbose_name': 'Academic_Writing_Requirement',
                'verbose_name_plural': 'Academic_Writing_Requirements',
            },
        ),
        migrations.CreateModel(
            name='Academic_Writing_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('pages', models.IntegerField(blank=True, default=0, null=True)),
                ('charts', models.IntegerField(blank=True, default=0, null=True)),
                ('slides', models.IntegerField(blank=True, default=0, null=True)),
                ('order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing')),
            ],
            options={
                'verbose_name': 'Academic_Writing_Detail',
                'verbose_name_plural': 'Academic_Writing_Details',
            },
        ),
    ]
