# Generated by Django 4.1 on 2022-08-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Writing_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('pages', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Academic_Writing_Detail',
                'verbose_name_plural': 'Academic_Writing_Details',
            },
        ),
        migrations.CreateModel(
            name='Academic_Writing_Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('instruction_file', models.FileField(upload_to='')),
                ('paper_format', models.CharField(max_length=200)),
                ('references', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Academic_Writing_Requirement',
                'verbose_name_plural': 'Academic_Writing_Requirements',
            },
        ),
        migrations.CreateModel(
            name='Academic_Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('Academic Writing', 'Academic Writing'), ('Programming Assignment', 'Programming Assignment'), ('Calculations Assignment', 'Calculations Assignment')], default='Academic Writing', max_length=200)),
                ('academic_year', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('paper_level', models.CharField(choices=[('Advanced', 'Advanced'), ('Standard', 'Standard'), ('Basic', 'Basic')], default='Standard', max_length=200)),
                ('upgrade', models.CharField(max_length=200, null=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing_detail')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing_requirement')),
            ],
            options={
                'verbose_name': 'Academic_Writing',
                'verbose_name_plural': 'Academic_Writing',
            },
        ),
    ]
