# Generated by Django 4.0 on 2022-11-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(blank=True, max_length=200, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline', models.CharField(blank=True, max_length=200, null=True)),
                ('paper_level', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('upgrade', models.CharField(blank=True, max_length=200, null=True)),
                ('paper_type', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('pages', models.IntegerField(blank=True, default=0, null=True)),
                ('charts', models.IntegerField(blank=True, default=0, null=True)),
                ('slides', models.IntegerField(blank=True, default=0, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('instruction_file', models.FileField(blank=True, null=True, upload_to='InstructionFiles/')),
                ('paper_format', models.CharField(blank=True, max_length=200, null=True)),
                ('references', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('prog_language', models.CharField(blank=True, max_length=200, null=True)),
                ('programming_category', models.CharField(blank=True, max_length=200, null=True)),
                ('task_size', models.CharField(blank=True, max_length=200, null=True)),
                ('software', models.CharField(blank=True, max_length=200, null=True)),
                ('discipline', models.CharField(blank=True, max_length=200, null=True)),
                ('spacing', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.user')),
            ],
            options={
                'verbose_name': 'Academic_Writing',
                'verbose_name_plural': 'Academic_Writing',
            },
        ),
    ]
