# Generated by Django 4.1 on 2022-08-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_academic_writing_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_writing_detail',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='academic_writing_requirement',
            name='order_type',
        ),
        migrations.AddField(
            model_name='academic_writing',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing_detail'),
        ),
        migrations.AddField(
            model_name='academic_writing',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing_requirement'),
        ),
    ]
