# Generated by Django 4.1 on 2022-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_academic_writing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_writing',
            name='amount',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='academic_writing',
            name='discipline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='academic_writing',
            name='prog_language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='academic_writing',
            name='programming_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='academic_writing',
            name='software',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='academic_writing',
            name='task_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
