# Generated by Django 4.1 on 2022-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_academic_writing_detail_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_writing',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
