# Generated by Django 4.1 on 2022-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_academic_writing_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_writing_requirement',
            name='references',
            field=models.IntegerField(default=1),
        ),
    ]
