# Generated by Django 4.1 on 2022-08-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_academic_writing_requirement_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_writing',
            name='details',
        ),
        migrations.RemoveField(
            model_name='academic_writing',
            name='requirements',
        ),
        migrations.AddField(
            model_name='academic_writing_detail',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing'),
        ),
        migrations.AddField(
            model_name='academic_writing_requirement',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.academic_writing'),
        ),
    ]
