# Generated by Django 4.0 on 2022-10-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_academic_writing_spacing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_writing',
            name='instruction_file',
            field=models.FileField(blank=True, null=True, upload_to='InstructionFiles/'),
        ),
    ]
