# Generated by Django 4.1 on 2022-08-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_academic_writing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_writing_detail',
            name='charts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='academic_writing_detail',
            name='slides',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='academic_writing',
            name='deadline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='academic_writing',
            name='upgrade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='academic_writing_detail',
            name='pages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='academic_writing_detail',
            name='paper_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='academic_writing_detail',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='academic_writing_requirement',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic_writing_requirement',
            name='paper_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='academic_writing_requirement',
            name='references',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
