# Generated by Django 4.1 on 2022-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_academic_writing_detail_charts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_writing',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
